id: 4c29ee13fcec4c9f82e878bbbb16fda4
initial_creation_type: ocr
source_metadata:
  volumes:
    771df76b795949efa843f1e868c544a0:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: སྟོང་པ་ཉིད་བདུན་ཅུ་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
